### ISSUE TITLE
Can't open browser from menu bar app or notification on Ubuntu 23 with Wayland, PopOS 22.04, potentially others

### ISSUE THREAD

**Issue by RebeccaMahany** [kolide/launcher#1537]
For Ubuntu 23 with Wayland: we rely on [Xwayland](https://github.com/kolide/launcher/blob/main/ee/desktop/runner/runner_linux.go#L262) to be running in order to grab the `DISPLAY`, which we need to be able to open URLs from the menu bar app and from notifications. I updated some software on Ubuntu 23.04 and now I don't have an `xwayland` process, just `gdm-wayland-session`, which does not have `DISPLAY` as an arg.

We've also had reports of the browser not opening on PopOS 22.04.

Overall, the way(s) that we're finding and setting `DISPLAY` is feeling increasingly brittle. We've had issues come up like this on the last several releases. This issue is for, at the very least, fixing the issue on Ubuntu 23.04 with wayland and PopOS, but ideally to find a less brittle way to set DISPLAY in general.

______________

## Workarounds

Consolidating some workarounds from the comments here:

### Ubuntu-specific workarounds

[Switching from wayland to x11 temporarily](https://askubuntu.com/a/961345) should let you open links from the menu bar app, and from notifications. After switching to x11, you will have to restart the launcher service via `sudo systemctl restart launcher.kolide-k2.service` first to get the menu bar app to show up.

### Registering your device when you can't access the registration URL from the menu bar app

Any route through auth will also force registration on an unregistered device, so attempting to log in to any Kolide-protected app should get you to the correct registration URL.

**Comment by rolandoscott** [comment]
I can confirm this is also happening for me on Ubuntu 23.10.. the tray icon appears.. the menu option appear.. but nothing happens when I click on them.. 

In the meantime, is there any way to trigger the "Register Device" option somehow else.. either via terminal or is it a specific URL that I can just go to?

**Comment by RebeccaMahany** [comment]
I know we discussed on https://github.com/kolide/launcher/issues/1543, just adding info on the workaround here for ease of access in case anyone else runs into it --

[Switching from wayland to x11 temporarily](https://askubuntu.com/a/961345) should let you open links from the menu bar app, and from notifications. After switching to x11, you will have to restart the launcher service via `sudo systemctl restart launcher.kolide-k2.service` first to get the menu bar app to show up.

**Comment by tobybellwood** [comment]
Just popping in here to say that I had the same issue as Rolando, except that my system is X11 (and has never been on Wayland). I ended up capturing the process call from the menubar click and visiting the registration URL myself.

Is it possible to get these URLs via the CLI anyway, or is the menubar icon the only option?

**Comment by RebeccaMahany** [comment]
Hey @tobybellwood, thanks for reporting -- would you mind passing along your OS/OS version too so we can make sure it's covered when we address this?

It's not possible to get these URLs via the CLI -- I will check to see if it's possible to get the URL another way and update.

**Comment by bomoko** [comment]
I'm having the same issues as described by @tobybellwood - I'm running X11 on Pop!_OS 22.04 LTS.

**Comment by tobybellwood** [comment]
Thanks @RebeccaMahany - I'm also running X11 on Pop!_OS 22.04 LTS

**Comment by RebeccaMahany** [comment]
@bomoko @tobybellwood -- You can grab the registration URL from a JSON file that stores the menu data, which is located at `/var/kolide-k2/k2device.kolide.com/menu.json`. (Thank you @James-Pickett for the proposed workaround. 🙂 ) I re-registered my device to confirm -- I think `jq -r '.items[0].action.action.url' /var/kolide-k2/k2device.kolide.com/menu.json` should do the trick.

**Comment by bomoko** [comment]
Thanks @RebeccaMahany - that worked like a charm.

**Comment by RebeccaMahany** [comment]
For anyone else experiencing this issue specifically with device registration in the future, an easier workaround: any route through auth will also force registration on an unregistered device, so attempting to log in to any Kolide-protected app should get you to the correct registration URL. 🙂

**Comment by RebeccaMahany** [comment]
At least for Ubuntu+wayland, I'm having success per [this](https://unix.stackexchange.com/a/709811) if I set `WAYLAND_DISPLAY` and `XDG_RUNTIME_DIR` in addition to the other env vars

**Comment by RebeccaMahany** [comment]
At least for Ubuntu and Debian, this issue should be addressed by today's release https://github.com/kolide/launcher/releases/tag/v1.5.3.

**Comment by piranhaphish** [comment]
I'm sorry for reviving this but this has been and continues to be an issue for me on Kubuntu (Ubuntu w/ KDE Plasma), even around the timeframe of this bug report.

The indicator appears in the tray, and the menu appears fine, but none of the menu items ever result in any action.

- Kolide Launcher 1.22.0
- Kubuntu 24.04.2 LTS
- kwin_wayland 5.27.11 
- XWayland 23.2.6

Inside the environment for launcher, I see the environment variables
DISPLAY=:1
WAYLAND_DISPLAY=wayland-0

I really do appreciate Kolide's commitment to Linux, and this has been the only real trouble point for me, so it would be great to see it resolved.

**Comment by RebeccaMahany** [comment]
Reopening per report above 🙂

**Comment by smlx** [comment]
I bind mounted this script to `/usr/bin/xdg-open` in the launcher environment to force opening via the session bus. Maybe the launcher should consider only using dbus on Linux?

```bash
#!/bin/sh
# Forward the URL directly to the XDG Desktop Portal via D-Bus
exec /usr/bin/busctl --user call org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.OpenURI OpenURI "ssa{sv}" "" "$1" 0
```

**Comment by piranhaphish** [comment]
I'm sorry @RebeccaMahany , I don't recall getting notified about this reply from you almost a year ago. Thank you for following up. I am still having this issue, so I replied with your requested info below.


> [@piranhaphish](https://github.com/piranhaphish) thank you for the report! launcher should use `xdg-open` when trying to open a URL from the menu bar, so I have some follow-up questions to see if we can figure out what's going wrong here specifically:
> 
> * What browser is used if you run `xdg-open https://google.com`?

Chromium 148.0.7778.167 (Official Build) (64-bit)

> * Output of `xdg-settings get default-web-browser`
  
org.chromium.Chromium.desktop

> * Was your default web browser installed with snap? (Check output of `snap list`)

Installed via Flatpak: app/org.chromium.Chromium/x86_64/stable

> * Output of `xdg-mime query default x-scheme-handler/https`

org.chromium.Chromium.desktop

> * Output of `echo $XDG_DATA_DIRS`

/home/{user}/.local/share/flatpak/exports/share /var/lib/flatpak/exports/share /usr/local/share /usr/share /var/lib/snapd/desktop

> * Output of `echo $XDG_RUNTIME_DIR` for good measure

/run/user/1000

> * If you have received a notification from Kolide and clicked it, do you remember if that opened in your browser, or if it also didn't do anything?

Didn't do anything.

> 
> I think there should also additionally be logs that might help us figure out what's going on for your device. If you can, could you click on a couple items in the menu to generate logs, and then send those to us by running `sudo /usr/local/kolide-k2/bin/launcher flare` (collects troubleshooting data about launcher, including all local logs)? After the command completes, you should see output that looks like:
> 
> ```
> time=2025-07-01T12:56:47.478Z level=INFO source=/Users/runner/work/launcher/launcher/cmd/launcher/flare.go:103 msg="flare creation complete" status="flare uploaded successfully" file=2025/07/01/01JZ30YDM552MCFQ4Q06RKQT6F.zip config_path=/etc/kolide-k2/launcher.flags
> ```
> 
> -- if you let me know what the file name is, I can take a look!

Uploaded: 2026/05/28/01KSQY5MSATJ0EEZFXP2TQMPSK.zip


Also, spurred by the suggestion from @smlx , I tried inspecting how `xdg-open` gets called. I see that it is indeed called with the URL requested by Kolide yet the browser doesn't open. When I manually call xdg-open myself with the same URL, it opens fine (no other arguments in either case). So it appears to be purely a matter of the context of the user invoking the command.

This is why @smlx 's suggestion probably worked, because he's translating the call into a fresh D-Bus context. Going on that, MrGPT and I did a bit more poking and found these differences:

Relevant env vars within the xdg-open context when called by Kolide:
```
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:1
WAYLAND_DISPLAY=wayland-0
XAUTHORITY=''
XDG_CURRENT_DESKTOP=''
DESKTOP_SESSION=''
XDG_SESSION_TYPE=''
BROWSER=''
GTK_USE_PORTAL=''
```

Same env vars when xdg-open is called by the user directly:
```
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:1
WAYLAND_DISPLAY=wayland-0
XAUTHORITY=/run/user/1000/xauth_pHsGKm
XDG_CURRENT_DESKTOP=KDE
DESKTOP_SESSION=plasmawayland
XDG_SESSION_TYPE=wayland
BROWSER=''
GTK_USE_PORTAL=''
```

Probably most importantly, `xdg-settings` called from within the Kolide-initiated context returns nothing, and calling `gio mime x-xcheme-handler-http` (and -https) returns "No default application …" whereas they return "org.chromium.Chromium.desktop" when called by the user directly.

Hope this helps.

**Comment by RebeccaMahany** [comment]
Hi @piranhaphish, thank you for the follow-up and the additional info! Just a quick update -- I retrieved the flare you uploaded, and I can see that the agent is failing to find the xauthority file. I will take a look at fixing that + anything else we're missing when the user is running KDE.

**Comment by piranhaphish** [comment]
Thanks @RebeccaMahany . Really looking forward to seeing this resolved.

**Comment by RebeccaMahany** [comment]
@piranhaphish this change went out in launcher v2.4.0, curious to see if the behavior has improved for you?

**Comment by piranhaphish** [comment]
Great! Thank you.

My org (Kelvin) doesn't show 2.4.0 available, only 2.1.1. I'll request 2.4.0 to be made available and let you know how it goes.

edit: A ticket was raised, but perhaps you could follow-up on that request @RebeccaMahany ?

**Comment by RebeccaMahany** [comment]
The agent should autoupdate to the latest version automatically without requiring a newer installer -- you can run `sudo /usr/local/kolide-k2/bin/launcher version` to check the running version of the agent. (sudo is required to access the autoupdate metadata on disk.) I'll check up on the support request regardless.

**Comment by RebeccaMahany** [comment]
@piranhaphish I did go ahead and get the Linux installers rebuilt for your org -- they are all on 2.4.0 now, so if you need to reinstall for whatever reason, you will immediately be running the latest version instead of having to wait an hour for autoupdate.

**Comment by piranhaphish** [comment]
Thanks @RebeccaMahany I saw with `launcher version` that it was indeed 2.4.0. Unfortunately I still don't see a difference. Clicking the links doesn't spawn a browser or open a tab in any existing browser window.

However, I do see the `XAUTHORITY` env variable being populated, but it didn't seem to make a difference.

```
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:1
WAYLAND_DISPLAY=wayland-0
XAUTHORITY=/run/user/1000/xauth_IFDFos
XDG_CURRENT_DESKTOP=''
DESKTOP_SESSION=''
XDG_SESSION_TYPE=''
BROWSER=''
GTK_USE_PORTAL=''
```

I tried force-restarting the launcher with `sudo systemctl restart launcher.kolide-k2.service` and even a full reboot just to be sure. But no luck.

**Comment by RebeccaMahany** [comment]
Just an internal note that this is now filed as KOL-1153, but I'm keeping the issue open here as well for communication and feedback.

**Comment by RebeccaMahany** [comment]
@piranhaphish -- The dbus change above shipped yesterday with launcher v2.5.0 -- whenever you get a chance, let me know if you see any changed behavior here?

**Comment by piranhaphish** [comment]
It works for me @RebeccaMahany.

Thank you! This really pulls the product together into a first-class solution, from my perspective. Thanks for all the work.

**Comment by RebeccaMahany** [comment]
Amazing, I am so glad to hear it's working!
